---
# Set up systemd service files to run Puma and workers

- name: Create Puma configuration
  copy: src=puma.rb dest=/opt/rletters/state/puma.rb
  tags: services

- name: Create Puma systemd service
  copy: src=rletters-puma.service dest=/etc/systemd/system
  tags: services

- name: Create systemd queue services
  copy: src=rletters-que.service dest=/etc/systemd/system
  tags: services

- name: Reload systemd services
  command: systemctl daemon-reload
  tags: services

- name: Start systemd services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rletters-puma
    - rletters-que
  tags: services

- name: Wait for systemd to bring up the Puma
  script: puma-wait.sh
  tags: services

- name: Run task expiration task every six hours via cron
  cron: name='Expire RLetters tasks' user='rletters_deploy' minute='0' hour='*/6' state='present' job='RAILS_ENV=production; cd /opt/rletters/root/ && bin/rails maintenance:expire_tasks >/dev/null 2>&1'
  tags: services
